export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
export const CHANGE_USER_CONFIRM_PASSWORD = 'CHANGE_USER_CONFIRM_PASSWORD';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ERROR_AUTH = 'ERROR_AUTH';
export const AUTH_LOADING = 'AUTH_LOADING';

export const CLEAR_INPUTS = 'CLEAR_INPUTS';

export const GET_DEALS = 'GET_DEALS';