export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
export const CHANGE_USER_CONFIRM_PASSWORD = 'CHANGE_USER_CONFIRM_PASSWORD';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ERROR_AUTH = 'ERROR_AUTH';
export const AUTH_LOADING = 'AUTH_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const CLEAR_INPUTS = 'CLEAR_INPUTS';

export const GET_DEALS = 'GET_DEALS';
export const GET_DEAL_BY_ID = 'GET_DEAL_BY_ID';
export const GET_MORE_DEALS = 'GET_MORE_DEALS';
export const CHANGE_FILTER_TYPE = 'CHANGE_FILTER_TYPE';

export const CHANGE_REVIEW_TEXT = 'CHANGE_REVIEW_TEXT';
export const CHANGE_REVIEW_RATING = 'CHANGE_REVIEW_RATING';
export const OPEN_ADDREVIEW_MODAL = 'OPEN_ADDREVIEW_MODAL';
export const CLOSE_ADDREVIEW_MODAL = "CLOSE_ADDREVIEW_MODAL";
export const SET_REVIEW_LOADING = 'SET_REVIEW_LOADING';
export const REMOVE_REVIEW_LOADING = 'REMOVE_REVIEW_LOADING';
export const REVIEW_ERROR = 'REVIEW_ERROR';
export const CLEAR_REVIEW_INPUTS = 'CLEAR_REVIEW_INPUTS';

export const GET_USER = 'GET_USER';
export const GET_USER_LISTOFDEALS = 'GET_USER_LISTOFDEALS';
export const PROFILE_USER_LOADING = 'PROFILE_USER_LOADING';
export const PROFILE_USER_REMOVELOADING = 'PROFILE_USER_REMOVELOADING';
export const PROFILE_DEALS_LOADING = 'PROFILE_DEALS_LOADING';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const IMAGE_LOADING = 'IMAGE_LOADING';
export const IMAGE_REMOVELOADING = 'IMAGE_REMOVELOADING';

export const CHANGE_DEALINFO = 'CHANGE_DEALINFO';
export const DEALFORM_ERROR = 'DEALFORM_ERROR';
export const CLEAR_DEALFORM_INPUTS = 'CLEAR_DEALFORM_INPUTS';
export const SET_DEALFORM_LOADING = 'SET_DEALFORM_LOADING';