export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ERROR_LOGIN_USER = 'ERROR_LOGIN_USER';